- frontend/src/components/categoryButtonArea/CategoryButton.tsx
- frontend/src/components/categoryButtonArea/CategoryButtonsHeader.tsx
- frontend/src/components/categoryButtonArea/index.tsx
> PR 경로 변경 수정

- backend/src/daos/goods.dao.ts
- backend/src/types/dto/goods.dto.ts
- backend/src/util/read-csv-goods-data.ts
> 상품 테이블의 컬럼이 변경되었으므로 이를 갱신함
- #16 
변경된 스키마 구조에 맞추어 데이터베이스 스키마를 변경
상품을 생성하는 SQL 문에서 create_at 등과 같은 내용을 자동화 해서 없앰
name과 같이 예약어가 column 명인 경우 명칭을 변경함
> PR: Schema 수정에 따른 DAO, DTO 갱신

- frontend/package.json
- frontend/src/components/home/Banner/Advertisement.tsx
- frontend/src/components/home/Banner/Indicator.tsx
- frontend/src/components/home/Banner/index.tsx
- frontend/yarn.lock
> 메인 페이지 (home)에서 사용할 광고 배너 컴포넌트 제작
- #24
flicking 라이브러리를 이용한 광고 배너 (이미지 슬라이드) 컴포넌트 추가
indicator의 경우는 dot이 아닌 숫자로 표시하도록 디자인함
이는 dot의 경우 clickable 한 UX이며, 10개 이상의 광고의 경우 dot이 많아져 UI적으로 위치하기 애매하기 때문
indicator는 자체 state(index)를 가지며 이 state의 변경은 상위 컴포넌트 (Banner)에서 observable 객체가 변경시켜줌
> PR: 광고 Banner 컴포넌트

- frontend/src/components/common/Layout/index.tsx
- frontend/src/stylesheets/index.css
> 프론트엔드 레이아웃 수정
- #29 
- 페이지 레이아웃 컨텐츠 부분 스크롤 설정
- 이미지 드래그 막기
> feat: 프론트엔드 레이아웃 수정

- frontend/src/components/home/MainItem/index.tsx
- frontend/src/components/home/Recommend/Header.tsx
- frontend/src/components/home/Recommend/List.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/Login.tsx
- frontend/src/router.tsx
> 라우팅 관련 오류 제거
- 페이지 라우팅 동작 오류 이전 버전으로 원복
- 불필요한 콘솔 삭제
> HOTFIX: 프론트엔드 페이지 라우팅 오류 수정

- frontend/src/components/home/MainItem/index.tsx
- frontend/src/components/home/Recommend/Header.tsx
- frontend/src/components/home/Recommend/List.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/Login.tsx
- frontend/src/router.tsx
라우팅 관련 오류 제거
배포 페이지에 적용하기 위해 PR 생성
> release: Fix routing error

- .prettierrc.js
> tab width가 달라 코드의 통일성이 깨지기 때문에, 설정파일을 적용
tab width와 semi 설정을 관리하는 prettierrc 파일 생성
> PR: prettier 설정파일 생성

- frontend/src/components/common/Layout/index.tsx
- frontend/src/components/home/PullTo/index.tsx
- frontend/src/pages/Home.tsx
- frontend/src/stylesheets/index.css
> PR: 당겨요 컴포넌트

- frontend/src/App.tsx
- frontend/src/components/home/MainItem/ItemPrice.tsx
- frontend/src/components/home/MainItemContainer/ChangeItemsButton.tsx
- frontend/src/components/home/MainItemContainer/index.tsx
- frontend/src/pages/Home.tsx
> 작업했던 부분에서 warning 부분 제거
- #56
> refactor: warnning 제거

- frontend/src/components/common/Layout/index.tsx
- frontend/src/components/home/Recommend/Header.tsx
- frontend/src/components/home/Recommend/Menus.tsx
- frontend/src/components/home/Recommend/Section.tsx
- frontend/src/components/home/Recommend/index.tsx
- frontend/src/pages/Home.tsx
> eslint에서 경고로 표시해주는 부분 삭제
eslint에서 경고로 표시해주는 부분 삭제
> PR: eslint warning 부분 제거

- backend/src/apis/goodsAPI.ts
- backend/src/apis/index.ts
- backend/src/daos/goods.dao.ts
- backend/src/server.ts
- backend/src/types/APIResponse.ts
- backend/src/types/dto/goods.dto.ts
> 키워드로 상품을 검색하는 API 추가
- #61
내용 어쩌구 저쩌구
왜 이 작업을 이렇게 했는지에 대한 설명
> PR: 상품검색 API

- frontend/src/ItemData.json
- frontend/src/components/common/CategoryMenu.tsx
- frontend/src/components/common/ItemList.tsx
- frontend/src/components/common/Layout/Header.tsx
- frontend/src/components/common/Layout/index.tsx
- frontend/src/components/common/index.ts
- frontend/src/components/home/CategoryButtonArea/CategoryButton.tsx
- frontend/src/components/home/CategoryButtonArea/CategoryButtonsHeader.tsx
- frontend/src/components/home/CategoryButtonArea/index.tsx
- frontend/src/components/home/MainItem/ItemContent.tsx
- frontend/src/components/home/MainItem/ItemContext.tsx
- frontend/src/components/home/MainItem/ItemImg.tsx
- frontend/src/components/home/MainItem/ItemPrice.tsx
- frontend/src/components/home/MainItem/index.tsx
- frontend/src/components/home/MainItemContainer/ChangeItemsButton.tsx
- frontend/src/components/home/MainItemContainer/index.tsx
- frontend/src/components/home/MainItemGallery/GalleryHeader.tsx
- frontend/src/components/home/MainItemGallery/GalleryImage.tsx
- frontend/src/components/home/MainItemGallery/index.tsx
- frontend/src/constants/message.ts
- frontend/src/mock.ts
- frontend/src/pages/Category.tsx
- frontend/src/pages/Home.tsx
- frontend/src/router.tsx
- frontend/src/stylesheets/index.css
> 카테고리 상품 컴포넌트 작업을 했다. (대분류, 소분류)
- #51 
- #50 
- #49 
- warning 제거
- 카테고리 이름 출력
- 카테고리 선택시 다시 소분류로 이동 (여기서는 카테고리는 더이상 안보임)
- 각 카테고리 컴포넌트에서 아이템 리스트 컴포넌트, 정렬 컴포넌트가 보임
- 정렬 컴포넌트에선 선택시 쉐도우 엘리먼트로 다른 영역은 선택안되고 정렬 선택만 됨
> 카테고리 상품 컴포넌트 작업

- .github/workflows/deploy.yml
> 한줄요약
- #65
- git action deploy.yml 파일 생성
> feat: Create deploy.yml

- frontend/src/pages/Home.tsx
> mockdata를 수정하면서 변경사항이 미반영 되었는데 해당 부분 수정
> home 화면 '지금필요한 생필품' 수정

- frontend/src/components/home/Recommend/List.tsx
- frontend/src/pages/Category.tsx
> 이전 경로로 Banner를 받아오게 설정한 코드를 수정
- #72
> HOTFIX: 공통컴포넌트로 옮긴 Banner 경로 수정

- .github/workflows/deploy.yml
> git action 파일 수정
- #65
- ec2에 접근하여 자동 배포하도록 수정
> git action 파일 수정

- frontend/src/pages/Home.tsx
> pages/Home.tsx 파일에 Banner 컴포넌트 경로 오류 수정
- 
- import path 오류 수정
> HOTFIX: 프론트엔드 홈 페이지 경로 오류

- frontend/src/constants/layout.ts
- frontend/src/pages/Home.tsx
> 땡겨요 컴포넌트가 동작하는 위치 & 크기 지정
땡겨요 컴포넌트의 최대 크기를 상수로 관리하고, 페이지 스크롤이 최 상단에 있는 경우만 땡겨요가 가능하도록 설정
또한 threshold 값을 두어, threshold 이하로 스크롤이 아래에 있는 경우 땡겨요 기능이 가능하도록 구성
> PR: 땡겨요 컴포넌트의 크기를 상수로 관리

- frontend/src/components/search/Searchbar/Seachbar.test.tsx
> PR: 검색 바 텍스트 입력, 텍스트 삭제 테스트

- frontend/src/components/goods/Counter.test.tsx
- frontend/src/components/goods/Counter.tsx
- frontend/src/components/goods/StyleComponent.tsx
- frontend/src/components/goods/index.tsx
- frontend/src/components/home/MainItem/ItemContent.tsx
> 상품 수량 입력 하는 컴포넌트를 테스트 했다.
- #92 
- 1~10사이의 수량만 가능한지 테스트 했다.
> 상품 수량 입력 컴포넌트 테스트

- backend/src/apis/goodsAPI.ts
- frontend/src/components/search/History/index.tsx
- frontend/src/components/search/Searchbar/index.tsx
- frontend/src/contexts/SearchContext.tsx
- frontend/src/fetch/goods/getGoodsByName.ts
- frontend/src/utils/localstorage.ts
> 각 유저별 상품 검색 기록 기능을 추가함
기본 기능만 추가하고, 추후 기능 발전은 다음 PR에서 이어서 할 예정
- #102 
기존 개별 상품 조회 API와 주소가 충돌하므로, 검색에 대한 기능을 의미하는 query 옵션을 추가함
검색한 query를 history에 추가하는 기능 추가
local storage 사용을 담당하는 util 함수 추가
검색 Context에 검색 기록을 보여주는 state 추가
> PR: 상품 검색 기록 기능 추가

- backend/src/daos/category.dao.ts
- backend/src/daos/user.dao.ts
- backend/src/util/passport.ts
> userAPI에서 로그인이 제대로 되지 않아 수정
- #141 
- login이 제대로 되지 않는 문제가 있어 수정함
- any 타입을 수정함. (제네릭으로 타입 받으니 수정한 부분들에 대해서 신경써서 사용해야 함!)
> userAPI 수정

- backend/src/apis/index.ts
- backend/src/apis/recommendAPI.ts
- backend/src/daos/goods.dao.ts
- frontend/src/components/home/Recommend/Goods/index.tsx
- frontend/src/components/home/Recommend/List.tsx
- frontend/src/components/home/Recommend/Menus.tsx
- frontend/src/components/home/Recommend/index.tsx
- frontend/src/fetch/goods/getRecommendGoods.ts
> 대표상품 정보를 hard coding된 정보에서 실제 데이터베이스 정보로 변경
대표상품 정보를 불러오는 API 제작
메인카테고리를 한번 훑고, 각 메인카테고리별로 4개의 대표 상품정보를 반환하는 API 제작
이 때 가져오는 정보는 랜덤
API 를 호출해 정보를 받아오도록 구성함
> PR: 대표상품 API 제작 및 적용

- backend/src/apis/goodsAPI.ts
- backend/src/daos/data-access-object.ts
- backend/src/daos/goods.dao.ts
GET: /api/goods/id/:goodId
> goodId는 숫자 문자열만 가능하다.  a123 형태는 404를 반환한다.
```
성공시 : HTTP/1.1 200 OK
{
"success": true,
"data" : {
goodId, 
title, 
categoryName,
createdAt, 
cost, 
discount, 
amount, 
imageUrl
}
}
실패시 : HTTP/1.1 404 OK
{
"success": false
}
```
> goodsAPI 중 goodId로 상품 상세 정보 받는 API

- backend/src/apis/categoryAPI.ts
- backend/src/daos/category.dao.ts
- backend/src/daos/goods.dao.ts
- frontend/src/components/cart/CartList/index.tsx
- frontend/src/components/common/CategoryMenu.tsx
- frontend/src/components/common/ItemList.tsx
- frontend/src/components/common/Layout/Header.tsx
- frontend/src/components/goods/index.tsx
- frontend/src/components/home/MainItemContainer/index.tsx
- frontend/src/components/home/MainItemGallery/GalleryImage.tsx
- frontend/src/components/home/MainItemGallery/index.tsx
- frontend/src/fetch/category/index.ts
- frontend/src/fetch/goods/getGoodsByGoodId.ts
- frontend/src/fetch/index.ts
- frontend/src/mock.ts
- frontend/src/pages/Category.tsx
- frontend/src/pages/Home.tsx
- frontend/src/types/Cart.ts
- frontend/src/types/Good.ts
- frontend/src/types/ItemType.ts
- frontend/src/utils/func.ts
> main 화면에 컴포넌트에 서버 연동, 연동에 필요한 유틸 함수 추가
> warning 제거 및 type 정리
- #116 
- main 화면 오늘 뭐 먹지? 지금 필요한 생필품!에 서버연동
- 서버 연동에 필요한 클라이언트 측 유틸 함수 추가
- warning 제거
- ItemType 정리 및 수정
- mock 데이터중 일부 제거
> main 화면 서버 연동, 로그인 일부 문제 수정

- backend/src/apis/categoryAPI.ts
- backend/src/apis/goodsAPI.ts
- backend/src/daos/goods.dao.ts
- backend/src/util/util.ts
- frontend/src/components/home/MainItem/ItemContext.tsx
- frontend/src/components/home/MainItem/ItemPrice.tsx
- frontend/src/fetch/category/index.ts
- frontend/src/pages/Home.tsx
> 메인 화면에 필요한 mainAPI를 개발했다.
- #144 
- #152 
- 사용자를 위해 준비한 상품 API 구현
- 새로 나왔어요 API 구현 
- 요즘 잘팔려요 API 구현 
- 사용자를 위해 준비한 상품 API 연동
- 지금 사면 번쩍 할인 API 연동
- 새로 나왔어요 API 연동
- 요즘 잘팔려요 API 연동
> main API 개발 및 main 페이지와 연동

- frontend/src/components/goods/index.tsx
> HOTFIX!: 프론트엔드 장바구니 아이템 타입 오류 수정

- frontend/src/components/home/MainItemContainer/index.tsx
- frontend/src/components/home/Recommend/Content.tsx
- frontend/src/components/home/Recommend/Menus.tsx
- frontend/src/components/search/Result/GoodInformation.tsx
- frontend/src/components/search/Result/index.tsx
> 홈화면 대표상품 컴포넌트 fixed 위치 수정 + 검색 결과에 할인율 표시
> PR: 홈화면 대표상품 컴포넌트 fixed 위치 수정 + 검색 결과에 할인율 표시

- frontend/src/components/home/MainItem/ItemImg.tsx
> feat: 찜버튼 효과 추가

- frontend/src/components/cart/CartList/CartItem.tsx
- frontend/src/components/cart/OrderBtn.tsx
- frontend/src/components/home/CategoryButtonArea/CategoryButton.tsx
- frontend/src/pages/Login.tsx
>  테스트하여 오류 및 추가 기능 구현
- 메인 페이지에서 카테고리 메뉴 이름이 길어지면 아래에 겹치는 현상이 있어 높이값을 추가
- 장바구니 페이지에서 상품 이미지 url s3 bucket 주소 붙도록 수정
- 장바구니 페이지에서 상품 이미지 누르면 상품 상세 페이지로 이동하도록 수정
- 로그인 페이지에서 이전 페이지로 이동할 수 있게 버튼 추가
> 프론트엔드 테스트 후 일부 수정

- frontend/src/components/goods/StyleComponent.tsx
- frontend/src/components/goods/index.tsx
- frontend/src/components/home/MainItem/ItemPrice.tsx
> 메인 아이템, 담기 스타일 수정, 값 콤마 추가, 이미지 url 추가
- 메인 아이템, 담기 스타일 수정 
- 값 콤마 추가
- 이미지 url 추가
> 메인 아이템, 담기 스타일 수정, 값 콤마 추가, 이미지 url 추가

- frontend/src/components/common/Layout/Header.tsx
- frontend/src/components/home/MainItem/ItemImg.tsx
> fix: warning 제거

- frontend/src/components/menu/index.tsx
- frontend/src/components/search/History/HistoryText.tsx
- frontend/src/components/search/Searchbar/index.tsx
- frontend/src/pages/Register.tsx
> PR: typescript warning 제거

- frontend/src/components/home/Recommend/Content.tsx
- frontend/src/components/home/Recommend/Goods/Detail.tsx
- frontend/src/components/home/Recommend/Goods/ItemPrice.tsx
- frontend/src/constants/layout.ts
> wrapper의 크기를 더 증가시키고, rem, em으로 설정되어있는 부분을 px로 변경
> PR: 대표상품 정보가 wrapper의 크기를 넘어서는 문제 수정

- backend/src/apis/cartAPI.ts
- backend/src/apis/userAPI.ts
> apidoc 작성된 부분 일부 수정

- frontend/src/components/home/CategoryButtonArea/CategoryButton.tsx
- frontend/src/components/home/MainItem/ItemImg.tsx
- frontend/src/components/home/MainItem/ItemPrice.tsx
- frontend/src/components/home/MainItem/index.tsx
- frontend/src/components/home/MainItemContainer/index.tsx
- frontend/src/pages/Category.tsx
- frontend/src/pages/Home.tsx
- MainItem width에 따른 상품 가격 위치 조정
- MainItem fontSize 수정
- CategoryButton의 word-break를 break-all로 수정 (사파리에서 '·'글자를 자르지 않기 때문에 break-all로 변경함)
> MainItem, CategoryButton 스타일 수정

- frontend/src/components/home/MainItemGallery/GalleryImage.tsx
> feat: 프론트엔드 이미지 갤러리 사이즈 수정

- README.md
> README 2차 업데이트
- #170
- api doc 링크 추가
- 데모 영상 유튜브 링크 추가
- gif 이미지 변경
- 기술적 도전 사항 추가
- ERD 이미지 변경
> feat: README 2차 업데이트

- frontend/src/components/common/Layout/Footer.tsx
- frontend/src/components/common/Layout/Header.tsx
- frontend/src/components/common/PopUp/index.tsx
- frontend/src/constants/message.ts
- frontend/src/contexts/CartContext.tsx
- frontend/src/fetch/user/getToken.ts
- frontend/src/pages/Home.tsx
- frontend/src/pages/Login.tsx
- 장바구니 개수 모든 페이지에서 보이도록 수정
- 메인 페이지 고객 이름 나오도록 수정
- 팝업 레이아웃 조정
- 장바구니 개수 추가 오류 수정
> 배포 테스트 후 일부 수정
